services:
  adguardhome:
    image: ghcr.io/feng2208/adguardhome:v0.107.73
    restart: 'unless-stopped'
    network_mode: 'host'
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
