services:
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin:2025092205
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /wd1-data/media
        target: /media
    restart: 'unless-stopped'
    # intel gpu hardware acceleration
    group_add:
      # /dev/dri/renderD128 group's id
      # getent group render | cut -d: -f3
      - '110'
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      
